# Generated by Django 5.2.9 on 2026-09-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rustdesdevice_is_deleted_rustdesdevice_deleted_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serverconfigversion',
            options={'ordering': ('-id',), 'verbose_name': '服务器配置版本', 'verbose_name_plural': '服务器配置版本列表'},
        ),
        migrations.AddField(
            model_name='rustdesdevice',
            name='hardware_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='硬件标识'),
        ),
        migrations.AddField(
            model_name='rustdesdevice',
            name='password_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='密码更新确认时间'),
        ),
    ]
