# Generated by Django 5.2.9 on 2026-09-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_serverconfigversion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rustdesdevice',
            name='last_reboot_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后重启指令时间'),
        ),
        migrations.AddField(
            model_name='rustdesdevice',
            name='rustdesk_service_running',
            field=models.BooleanField(default=True, verbose_name='RustDesk服务正常运行'),
        ),
    ]
