# Generated by Django 5.2.9 on 2026-09-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rustdesdevice_last_reboot_requested_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAppRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('windows', 'Windows'), ('linux', 'Linux')], db_index=True, max_length=20)),
                ('version', models.CharField(default='v1.0.0', max_length=50)),
                ('file', models.FileField(upload_to='apps/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('filesize', models.BigIntegerField(default=0)),
                ('release_notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('download_count', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.CharField(blank=True, default='', max_length=150)),
            ],
            options={
                'verbose_name': '客户端安装包',
                'verbose_name_plural': '客户端安装包列表',
                'ordering': ('-uploaded_at',),
            },
        ),
    ]
