# Generated by Django 5.2.9 on 2026-09-12 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_rustdesdevice_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='角色名称')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='角色标识')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='角色描述')),
                ('is_system', models.BooleanField(default=False, verbose_name='系统角色')),
                ('permissions', models.JSONField(blank=True, default=list, verbose_name='权限列表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
            ],
            options={
                'verbose_name': '用户角色',
                'verbose_name_plural': '用户角色列表',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='custom_permissions',
            field=models.JSONField(blank=True, default=list, verbose_name='独立权限覆盖'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rid',
            field=models.CharField(blank=True, max_length=16, verbose_name='RustDesk ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rtype',
            field=models.CharField(blank=True, max_length=20, verbose_name='rtype'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uuid',
            field=models.CharField(blank=True, max_length=60, verbose_name='uuid'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.userrole', verbose_name='用户角色'),
        ),
    ]
