# Generated by Django 5.2.9 on 2026-09-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_userprofile_is_approved_alter_userprofile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerConfigVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0, verbose_name='服务器配置版本')),
                ('server_host', models.CharField(default='', max_length=255, verbose_name='中继/ID服务器地址')),
                ('server_key', models.CharField(default='', max_length=255, verbose_name='服务器公钥')),
                ('hbbs_port', models.CharField(default='21116', max_length=10, verbose_name='HBBS端口')),
                ('hbbr_port', models.CharField(default='21117', max_length=10, verbose_name='HBBR端口')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='变更时间')),
                ('updated_by', models.CharField(blank=True, default='', max_length=150, verbose_name='变更管理员')),
            ],
            options={
                'verbose_name': '服务器配置版本',
                'verbose_name_plural': '服务器配置版本列表',
            },
        ),
        migrations.AddField(
            model_name='rustdesdevice',
            name='config_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='配置更新时间'),
        ),
        migrations.AddField(
            model_name='rustdesdevice',
            name='config_version',
            field=models.IntegerField(default=0, verbose_name='配置版本'),
        ),
    ]
