# Generated by Django on 2026-09-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_serverconfigversion_rustdesdevice_config_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rustdesdevice',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='已软删除'),
        ),
        migrations.AddField(
            model_name='rustdesdevice',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='软删除时间'),
        ),
    ]
