# Generated by Django 5.2.9 on 2026-09-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_clientapprelease'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientapprelease',
            name='is_latest',
            field=models.BooleanField(default=False),
        ),
    ]
