# Generated by Django 5.2.9 on 2026-09-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_clientapprelease_is_latest'),
    ]

    operations = [
        migrations.AddField(
            model_name='rustdesdevice',
            name='current_server_host',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='当前服务地址'),
        ),
        migrations.AddField(
            model_name='rustdesdevice',
            name='migrated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后迁移时间'),
        ),
        migrations.AddField(
            model_name='rustdesdevice',
            name='migration_pending',
            field=models.BooleanField(default=False, verbose_name='迁移挂起'),
        ),
    ]
