# Generated by Django 6.1.1 on 2026-09-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rustdesdevice_current_server_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rustdesdevice',
            name='fcm_token',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='FCM Token'),
        ),
        migrations.AddField(
            model_name='rustdesdevice',
            name='fcm_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='FCM Token更新时间'),
        ),
    ]
